version: "3.8"

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    # ports:
    #   - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  ollama-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    environment:
      - BEARER_TOKEN=<your_secret_token_here>
    ports:
      - "8080:8080"
    depends_on:
      - ollama

volumes:
  ollama_data:
